name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install -y libappindicator-dev make gcc
      - name: Build
        run: make ideapad-acpi-tray
      - name: Package
        uses: actions/upload-artifact@v3
        with:
          name: ideapad-acpi-tray
          path: |
            ideapad-acpi-tray
            LICENSE
            TRAY_LICENSE
            README.md
